# Nomail 設定ファイル

# 配信可能なローカルユーザー
#localuser	negi,mer

# ローカルな配信とみなすローカルドメイン
#localdomain	local.or.jp

# インターネットにメールを出す時のメールアドレス（必須）
internetaddr	negi@provider.ne.jp

# プロバイダの SMTP ホスト（必須）
smtphost	smtp.provider.ne.jp

# プロバイダの SMTP ポート（通常変更不要）
#smtpport	25

# インターネットにメールを出す時にヘッダのアドレスを書換える
#rewriteaddr	yes

# インターネットにメールを出す時に Message-Id: を削除する
#invalid_msgid	yes

# プロバイダの SMTP サーバに接続する時にタイムアウト。単位は秒
#timeout	60

# ローカルメーラの指定（詳しい方向け）
#local_mda	/usr/bin/procmail -d
